### ISSUE TITLE
Error in MarkYourLocation 

### ISSUE THREAD

**Issue by kenchoong** [solocoinapp/solocoin-android#24]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.shimadove.coronago, PID: 13575
    java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
        at com.shimadove.coronago.MarkYourLocationActivity.onSuccess(MarkYourLocationActivity.java:38)
        at com.shimadove.coronago.MarkYourLocationActivity.onSuccess(MarkYourLocationActivity.java:34)
        at com.google.android.gms.tasks.zzn.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

Step to reproduce : 
1) Branch "welcomePage"

2) PermissionActivity, click on "Access your location"
3) Then will go to MarkYourLocation.java
 4) Then will get the error above..

**Comment by adityasonel** [comment]
Null check added in location callback onSuccessListener, check commit https://github.com/coronagoapp/coronago/commit/d56ef6e9fd519bab8459b444a2e18812554e6e61

this issue occur when application doesn't able to get location permission or unable to access GPS.  Please check again!
